branches:
  only:
  - master
language: java
jdk:
- oraclejdk8
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
addons:
  apt:
    packages:
    - graphviz
  sonarcloud:
    token:
      secure: l45J1abRLCWp3CxqT+x8J76COCsjY6HUuBgHeycgrtkwSZyjV595+CncHAmHaSBuTSxc0FH3npNLOUDZyIvXXDxYvJ0nALKdvF6tsT4BTqABNl0/PS2WaBOk3FHDs50nd16jGpC5zV+NPIus+8YarjVMmK7z9nYpv23MCoGpXYk=
  ssh_known_hosts:
  - github.com
  - site.trajano.net:6022
env:
  global:
    secure: f4I6mz3SxSKIRECe3I+wA/HWmWgwvAqGQdjeTpi+tBOmjyz6GE5rbY1ozUbdHzBvog2IJAzbfRiUF5PEzhpNzqyIRqrxKIy1ahlnGzxV9MIn3hUBzLStvSMKlIJIrPlHf77+1bXNqOqpZzxj2GLlgs34ey8QkITmgPKIaPm/eV4=
before_install:
- openssl aes-256-cbc -K $encrypted_95322324a4e0_key -iv $encrypted_95322324a4e0_iv
  -in deploy-keys.tar.enc -out deploy-keys.tar -d
- tar xf deploy-keys.tar -C $HOME
install:
- tar xf deploy-keys.tar -C $HOME && chmod go-rwx -R $HOME/.m2 $HOME/.ssh
before_script:
- mvn clean
script:
- mvn package sonar:sonar -Dmaven.test.failure.ignore=true
deploy:
- provider: script
  skip_cleanup: true
  script: mvn -e deploy && mvn -e site-deploy
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: printf 'scm.tag=%1s\nscm.url=scm:git:https://git@github.com/%2s.git' "${TRAVIS_TAG}"
    "${TRAVIS_REPO_SLUG}" > release.properties && mvn release:perform
  on:
    tags: true
